# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_find_overlaps_indexed <- function(q_start, q_end, q_seq, q_strand, s_start, s_end, s_seq, s_strand, s_original, partition_keys, partition_starts, partition_ends, block_starts, block_ends, block_first_start, block_max_end, partition_block_starts, partition_block_ends, max_gap, min_overlap, type, ignore_strand, threads, deterministic) {
    .Call(`_fastRanges_cpp_find_overlaps_indexed`, q_start, q_end, q_seq, q_strand, s_start, s_end, s_seq, s_strand, s_original, partition_keys, partition_starts, partition_ends, block_starts, block_ends, block_first_start, block_max_end, partition_block_starts, partition_block_ends, max_gap, min_overlap, type, ignore_strand, threads, deterministic)
}

cpp_count_overlaps_indexed <- function(q_start, q_end, q_seq, q_strand, s_start, s_end, s_seq, s_strand, partition_keys, partition_starts, partition_ends, block_starts, block_ends, block_first_start, block_max_end, partition_block_starts, partition_block_ends, max_gap, min_overlap, type, ignore_strand, threads) {
    .Call(`_fastRanges_cpp_count_overlaps_indexed`, q_start, q_end, q_seq, q_strand, s_start, s_end, s_seq, s_strand, partition_keys, partition_starts, partition_ends, block_starts, block_ends, block_first_start, block_max_end, partition_block_starts, partition_block_ends, max_gap, min_overlap, type, ignore_strand, threads)
}

